[platformio]
default_envs = matrixbit

[env:matrixbit]
platform = espressif32 @ 7.1.3
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = -<*> +<main.cpp>
lib_deps =
    adafruit/Adafruit SSD1306 @ ^2.5.13
    adafruit/Adafruit NeoPixel @ ^1.12.3

[env:demo]
extends = env:matrixbit
build_src_filter = -<*> +<demo.cpp>
