[platformio]
default_envs = matrixbit

[env:matrixbit]
platform = espressif32 @ 7.1.3
board = matrixbit
framework = arduino
monitor_speed = 115200
build_src_filter = -<*> +<main.cpp>

[env:demo]
extends = env:matrixbit
build_src_filter = -<*> +<demo.cpp> +<demo/*.cpp>
lib_deps =
    https://github.com/lsongdev/arduino-oled-menu.git#fbc73478e02c6f3f8a7ff56aa53c6c910b90e2a1
